### ISSUE TITLE
CR LF 처리

### ISSUE THREAD

**Issue by chaejin-jen** [nyeoni/eyeRsee#59]
## Bug 개요
- '\n' 단위로 command line 을 파싱해서 문제 발생
  - "aaaaaaaa\r\nbbb\r\n" 의 경우 "bbbaaaaa" 같은 형태로 만들어짐
## Solution
- "\r\n" 단위로 command line 파싱
- [미정] nc로 테스트시, "\r\n" 으로
## Todos
- [ ]

**Comment by nyeoni** [comment]
`recv_buf.rfind()` 로 해결완료
